name: stayclose
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^17.2.0
  uuid: ^4.4.0
  timezone: ^0.9.2
  image_picker: ^1.0.4
  crop_your_image: ^2.0.0
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/